version: "2"
services:
  web:
    build: .
    labels:
      - "SERVICE_8080_NAME=github-bot-service"
      - "SERVICE_TAG=github-bot-serviceTag"
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"